config/routes.rb
Rails.application.routes.draw do
  resources :privates
  devise_for :users
  resources :users, :only => [:show]

  root to: "privates#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :user
  belongs_to :private
end

app/models/private.rb
class Private < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  has_many :event_attendees
  has_many :attendees, class_name: 'User', foreign_key: :user_id, through: :event_attendees, source: :user

  scope :past, -> { where('event_date < ?', Date.current) }
  scope :upcoming, -> { where('event_date >= ?', Date.current) }

  validates :title_of_event, presence: true, uniqueness: true
  validates :event_date, presence: true, uniqueness: true
  validates :description, presence: true, length: { minimum: 50, maximum: 1000 }
  validates :location, presence: true, length: { minimum: 10, maximum: 1000 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :privates, foreign_key: 'creator_id'
  has_many :event_attendees
  has_many :attending_events, foreign_key: :private_id, class_name: 'Private', through: :event_attendees,
                              source: :private

  #  belongs_to :creator class_name: "User", foreign_key: "creator"
  # validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 30, case_sensitive: false }

  def email_required?
    false
  end

  def password_required?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username])
  end
end

app/controllers/privates_controller.rb
class PrivatesController < ApplicationController
  before_action :set_private, only: %i[show edit update destroy]

  # GET /privates or /privates.json
  def index
    @past_events = Private.past
    @future_events = Private.upcoming
  end

  # GET /privates/1 or /privates/1.json
  def show
    @private = Private.find(params['id'])
    @attendees = @private.attendees
  end

  # GET /privates/new
  def new
    @private = Private.new
  end

  # GET /privates/1/edit
  def edit; end

  # POST /privates or /privates.json
  def create
    @private = current_user.privates.build(private_params)

    respond_to do |format|
      if @private.save
        format.html { redirect_to @private, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @private }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @private.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /privates/1 or /privates/1.json
  def update
    respond_to do |format|
      if @private.update(private_params)
        format.html { redirect_to @private, notice: 'Private was successfully updated.' }
        format.json { render :show, status: :ok, location: @private }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @private.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /privates/1 or /privates/1.json
  def destroy
    @private.destroy
    respond_to do |format|
      format.html { redirect_to privates_url, notice: 'Private was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_private
    @private = Private.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def private_params
    params.require(:private).permit(:event_date, :location, :description, :title_of_event)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:username)
  end

  def account_update_params
    params.require(:user).permit(:username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @created_events = current_user.privates
    @user_past_events = current_user.attending_events.past
    @user_upcoming_events = current_user.attending_events.upcoming
    @past_events = Private.past
    @future_events = Private.upcoming
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/privates_helper.rb
module PrivatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
        <% if flash[:notice] %>
  <div class="notification is-primary">
   <p class="notice"><%= notice %></p>
</div>
<% end %>
 <% if flash[:alert] %>
  <div class="notification is-danger">
       <p class="alert"><%= alert %></p>
  </div>
<% end %>
       <div>
       <nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      <img src="https://logos-download.com/wp-content/uploads/2019/11/Eventbrite_Logo-700x700.png" width="112" height="100">
    <%end%>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
                <% if user_signed_in? %>

 <%= link_to 'Create Event', new_private_path, class: "color" %>
 <% end %>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
            <% if user_signed_in? %>
<%= link_to "profile", current_user %>
                                <strong class="button">    <%= current_user.username%></strong>

                        <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "button is_danger" %>
                        <% else %>
            <%= link_to "Sign Up", new_user_registration_path, class: "button is_primary" %>
                                                <%= link_to "Log In", user_session_path, class: "button is_primary" %>

            <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>
       </div>
    <%= yield %>
  </body>
</html>

app/views/privates/_event.html.erb
<section>
    <% @privates.find_each do |private| %>
      <div class="post-container">
      <p>
  <strong>Event Title:</strong>
  <%= private.title_of_event %>
</p>
 <p>
  <strong>Event Date:</strong>
  <%= private.event_date %>
</p>
 <p>
  <strong>Event description:</strong>
  <%= private.description %>
</p>
 <p>
  <strong>Location:</strong>
  <%= private.location %>
</p>
        <%= link_to 'Show', private %>

<% end %>
  </section>  

<%= link_to 'Create Event', new_private_path


<%# <%= link_to 'Create Event', new_private_path %>

app/views/privates/_form.html.erb
<%= form_with(model: private) do |form| %>
  <% if private.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(private.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% private.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= form.label :title_of_event %>
    <%= form.text_field :title_of_event %>
  </div>
  <div class="field">
    <%= form.label :event_date %>
    <%= form.date_field :event_date %>
  </div>
   <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
   <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/privates/edit.html.erb
<h1>Editing Private</h1>

<%= render 'form', private: @private %>

<%= link_to 'Show', @private %> |
<%= link_to 'Back', privates_path %>

app/views/privates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Events</h1>


<h2>Upcoming Events</h2>
<% @future_events.each do |private| %>
<div class="event-data">
<p>
  <strong>Title:</strong>

  <%= private.title_of_event %>
</p>

<p>
  <strong>Creator:</strong>
  <%= private.creator['username'] %>
</p>
<p>
  <strong>Date:</strong>
  <%= private.event_date %>
</p>
            <% if user_signed_in? %>

        <td><%= link_to 'See more', private %></td>
<% end %>
</div>
<% end %>

<div class="border-bottom"></div>

<h2>Past Events</h2>

<% @past_events.each do |private|%>
<div class="event-data">
<p>
  <strong>Title:</strong>
  <%= private.title_of_event %>
</p>
<p>
  <strong>Creator:</strong>
  <%= private.creator['username'] %>
</p>
<p>
  <strong>Date:</strong>
  <%= private.event_date %>
</p>
</div>
<% end %>
 <br/> 

app/views/privates/new.html.erb
<h1>New Private</h1>

<%= render 'form', private: @private %>

<%= link_to 'Back', privates_path %>

app/views/privates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event Creator:</strong>
  <%= @private.creator['username'] %>
</p>
<p>
  <strong>Event date:</strong>
  <%= @private.event_date %>
</p>
<p>
  <strong>Event Title:</strong>
  <%= @private.title_of_event %>
</p>

<p>
  <strong>Event description:</strong>
  <%= @private.description %>
</p>
<p>
  <strong>Event Location:</strong>
  <%= @private.location %>
</p>
<div class="border-bottom"></div>
<div>
<p>
<strong>Attendess:
</strong>
<ul>

    <% @attendees.each do |attendee| %>
        <li><%= attendee.username %></li>
    <% end %>
   
</ul>
</p>

</div>

<%= link_to 'Edit', edit_private_path(@private) %> |  
<%= link_to 'Back', privates_path %>

app/views/users/show.html.erb
<h1> Hello
<%= @user.username %></h1>
<h2>Your Events</h2>
  <% @created_events.each do |private| %>
<p>
  <strong>Event Title:</strong>
  <%= private.title_of_event %>
</p>
 <p>
  <strong>Event Date:</strong>
  <%= private.event_date %>
</p>
 <p>
  <strong>Event description:</strong>
  <%= private.description %>
</p>
 <p>
  <strong>Location:</strong>
  <%= private.location %>
</p>
<div class="border-bottom"></div>
<% end %>

<h2>Upcoming Event</h2>
<ul>
    <% @future_events.each do |private| %>
        <li><%= private.title_of_event %> | <%= private.event_date %></li>
    <% end %>
</ul>

<h2>Attended Event</h2>
<ul>
    <% @past_events.each do |private| %>
        <li><%= private.title_of_event %> | <%= private.event_date %></li>
    <% end %>
</ul>